config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'static_pages#home'
  devise_for :users
  resources :transactions
  resources :groups

  get '/external', to: 'static_pages#external'
  get '/friends', to: 'static_pages#friends'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :transactions

  validates :name, presence: true, length: { maximum: 20 }
  validates :icon, presence: true
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :user
  belongs_to :group, optional: true

  validates :name, presence: true, length: { maximum: 20 }
  validates :amount, presence: true, numericality: { less_than_or_equal_to: 100_000, greater_than: 1 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :name, presence: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :transactions
  has_many :groups
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!

  def index
    @groups = Group.all
  end

  def new
    @group = Group.new
  end

  def show
    @group = current_user.groups.find(params[:id])
    @transaction = @group.transactions
    @total = @transaction.sum(:amount)
  end

  def create
    @group = current_user.groups.new(fields_arr)

    if @group.save

      redirect_to groups_path
    else
      render :new

    end
  end

  def edit
    @group = current_user.groups.find(params[:id])
  end

  def update
    @group = current_user.groups.find(params[:id])
    if @group.update(fields_arr)

      redirect_to groups_path, notice: 'Group was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /groups/1.json
  def destroy
    @group = current_user.groups.find(params[:id])
    @group.destroy

    redirect_back(fallback_location: root_path)
  end

  private

  def fields_arr
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :authenticate_user!

  def home; end

  def external
    user = User.find_by(id: current_user.id)
    @external_user_transactions = user.transactions.where(group_id: nil).order(created_at: :desc)
    @external_total = @external_user_transactions.sum(:amount)
  end

  def friends
    @users = User.where.not(id: current_user.id)
    @expenses = Transaction.where.not(user_id: current_user.id).all
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :authenticate_user!

  def index
    @transaction = current_user.transactions.all
    @other_transaction = @transaction.where.not(group_id: nil)
    @other_transaction_sorted = @other_transaction.includes([:group]).sort_by(&:created_at).reverse

    @total = @other_transaction.sum(:amount)
  end

  def new
    @transaction = Transaction.new
  end

  def create
    @transaction = current_user.transactions.new(transaction_params)

    if @transaction.save

      if @transaction.group_id.nil?

        redirect_to external_path, notice: 'Transaction expense was successfully created.'

      else

        redirect_to transactions_path, notice: 'Transaction was successfully created.'

      end

    else

      render :new

    end
  end

  def show
    @transaction = Transaction.find(params[:id])
  end

  def edit
    @transaction = current_user.transactions.find(params[:id])
  end

  def update
    @transaction = current_user.transactions.find(params[:id])
    if @transaction.update(transaction_params)

      if @transaction.group_id.nil?

        redirect_to external_path, notice: 'external transaction was successfully updated.'
      else
        redirect_to transactions_path, notice: 'transaction was successfully updated.'
      end

    else
      render :edit
    end
  end

  def destroy
    @transaction = current_user.transactions.find(params[:id])
    @transaction.destroy
    redirect_back(fallback_location: root_path)
  end

  private

  def transaction_params
    params.require(:transaction).permit(:name, :amount, :group_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
# rubocop:disable Style/GuardClause

module GroupsHelper
  def edit_delete_btn(user, group)
    if group.user_id == user.id
      links = [link_to('edit', edit_group_path(group), class: 'btn btn-primary edit_btn'), link_to('delete', group_path(group), class: 'btn btn-danger delete_grp_btn', data: { confirm: 'Are you sure?' }, method: :delete)]

      content_tag(:span) do
        links.collect do |l|
          concat content_tag(:span, l)
        end
      end
    end
  end
end

# rubocop:enable Style/GuardClause

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/groups/_form.html.erb
<%= form_for @group do |f| %>
  <% if @group.errors.any? %>
    <ul>
      <% @group.errors.full_messages.each do |msg| %>
        <li class="error"><%= msg %></li>
      <% end %>
    </ul>
  <% end %>
  <%= f.label :name %><br />
  <%= f.text_field :name %><br />
  <p class = "icons_grp">
    <b >Icon</b><br />
    <%= f.radio_button :icon, 'fa fa-bus' %><i class="fa fa-bus" aria-hidden="true"></i><br />
    <%= f.radio_button :icon, 'fa fa-briefcase' %> <i class="fa fa-briefcase" aria-hidden="true"></i><br />
    <%= f.radio_button :icon, 'fa fa-calculator' %> <i class="fa fa-calculator" aria-hidden="true"></i><br />
  </p>
  <%= f.submit class: "submit text-center btn btn-primary" %>
<% end %>

app/views/groups/edit.html.erb
<div class="form_app container">
  <h2>edit group</h2>
  <%= render 'form', group: @group %>
</div>

app/views/groups/index.html.erb
<section class="transaction_header">
  <div class="container t-d">
    <div class="button">
      <%= link_to root_path do %>
        <i class="fa fa-bars" aria-hidden="true"></i>
      <% end %>
    </div>
    <div class="title">
      Groups
    </div>
    <div class="search">
      <i class="fa fa-search" aria-hidden="true"></i>
    </div>
  </div>
  <h3 class ="text-center">most recent</h3>
</section>
<section class="transaction_body">
  <div class="container t-c">
    <% @groups.each do |g| %>
      <a href= "groups/<%=g.id%>" >
        <div class="card mb-3">
          <div class="row no-gutters">
            <div class="col-md-4 grp-icn">
              <i class= "<%= g.icon %>" ></i>
            </div>
            <div class="col-md-8">
              <div class="card-body">
                <h5 class="card-title"> <%= g.name %> </h5>
                <p class="card-text"><small class="text-muted"><%= g.created_at %></small></p>
                <%=  edit_delete_btn(current_user, g) %>
              </div>
            </div>
          </div>
        </div>
      </a>
    <% end %>
  </div>
  <br>
  <br>
  <%= link_to "Add new", new_group_path , :class => "btn btn-success  new_trans" %>
</section>

app/views/groups/new.html.erb
<div class="form_app container">
  <h2>new group</h2>
  <%= render 'form', group: @group %>
</div>

app/views/groups/show.html.erb
<section class="transaction_header">
  <div class="container t-d">
    <div class="button">
      <%= link_to root_path do %>
        <i class="fa fa-bars" aria-hidden="true"></i>
      <% end %>
    </div>
    <div class="title">
      Transactions for a specific group
    </div>
    <div class="search">
      <i class="fa fa-search" aria-hidden="true"></i>
    </div>
  </div>
  <h3 class ="text-center">most recent</h3>
</section>
<section class="transaction_body">
  <div class="total_amount_sec">
    <div class="amount_title">
      total amount
    </div>
    <div class="actual_total_amount">
      $ <%= @total %>
    </div>
  </div>
  <div class="container t-c">
    <% @transaction.each do |t| %>
      <div class="card mb-3">
        <div class="row no-gutters">
          <div class="col-md-4 grp-icn">
            <i class= "<%= t.group.icon %>" ></i>
          </div>
          <div class="col-md-8">
            <div class="card-body">
              <h5 class="card-title  trns"> <%= t.name %> </h5>
              <p class="card-text style-up"> <span>$</span> <%= t.amount %></p>
              <p class="card-text"> <span>created by</span> <%= t.user.name %></p>
              <p class="card-text"><small class="text-muted"><%= t.created_at %></small></p>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <br>
  <br>
  <%= link_to "Add new", new_transaction_path , :class => "btn btn-success  new_trans" %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinanceTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://fonts.googleapis.com/css2?family=Oleo+Script:wght@700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Odibee+Sans&display=swap" rel="stylesheet">

    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  </head>

  <body>
   <% if flash[:notice] %>
  			<p class="notice"><%= notice %></p>
  	<% end %>
  	<% if flash[:alert] %>
  			<p class="alert"><%= alert %></p>
  	<% end %>
   
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js" integrity="sha384-1CmrxMRARb6aLqgBO7yyAxTOQE2AKb9GfXnEo760AUcUmFx3ibVJJAzGytlQcNXd" crossorigin="anonymous"></script>
  </body>
</html>

app/views/static_pages/external.html.erb
<section class="transaction_header">
  <div class="container t-d">
    <div class="button">
      <%= link_to root_path do %>
        <i class="fa fa-bars" aria-hidden="true"></i>
      <% end %>
    </div>
    <div class="title">
      Extra transactions
    </div>
    <div class="search">
      <i class="fa fa-search" aria-hidden="true"></i>
    </div>
  </div>
  <h3 class ="text-center">most recent</h3>
</section>
<section class="transaction_body">
  <div class="total_amount_sec">
    <div class="amount_title">
      total amount
    </div>
    <div class="actual_total_amount">
      $ <%= @external_total %>
    </div>
  </div>
  <div class="container t-c">
    <% @external_user_transactions.each do |t| %>
      <div class="card mb-3">
        <div class="row no-gutters">
          <div class="col-md-4 grp-icn">
            <i class="fa fa-file-o" aria-hidden="true"></i>
          </div>
          <div class="col-md-8">
            <div class="card-body">
              <h5 class="card-title trns"> <%= t.name %> </h5>
              <p class="card-text style-up"> <span>$</span> <%= t.amount %></p>
              <p class="card-text"><small class="text-muted"><%= t.created_at %></small></p>
              <%= link_to "edit", edit_transaction_path(t), :class => "btn btn-primary edit_btn" %>
              <%= link_to "delete", transaction_path(t), :class => "btn btn-danger delete_grp_btn", data: {confirm: "Are you sure?"}, :method => :delete %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <br>
  <br>
  <%= link_to "Add new", new_transaction_path , :class => "btn btn-success  new_trans" %>
</section>

app/views/static_pages/friends.html.erb
<div class="container">
  <div class="button t-d">
    <%= link_to root_path do %>
      <i class="fa fa-bars" aria-hidden="true"></i>
    <% end %>
  </div>
  <%  @users.each do |user| %>
    <div class="card cd">
      <div class="card-header usr">
        Friend: <span> <%= user.name %> </span>
      </div>
    </div>
  <% end %>
</div>

app/views/static_pages/home.html.erb
<div class="profile_page container">
  <div class="log_out_btn text-right">
    <%= link_to "Log Out", destroy_user_session_path, :class => "btn btn-danger", method: :delete %>
  </div>
  <section class="profile_image">
    <div class="avator_image text-center">
      <%= image_tag("avator.png", :alt => "avator") %>
    </div>
    <div class="user_name text-center">
      <%= current_user.name %>
    </div>
  </section>
  <section class="menu">
    <ul>
      <li>
        <i class="fa fa-cog" aria-hidden="true"></i><%= link_to "All My transactions", transactions_path , :class => "btn" %>
      </li>
      <hr>
      <li>
        <i class="fa fa-map-marker" aria-hidden="true"></i> <%= link_to "All my External Transactions", external_path, :class => "btn" %>
      </li>
      <hr>
      <li>
        <i class="fa fa-plus-square" aria-hidden="true"></i> <%= link_to "All groups",  groups_path, :class => "btn" %>
      </li>
      <hr>
      <li>
        <i class="fa fa-plus-square" aria-hidden="true"></i> <%= link_to "friends",  friends_path, :class => "btn" %>
      </li>
    </ul>
  </section>
</div>

app/views/transactions/_form.html.erb
<%= form_for @transaction do |f| %>
  <% if @transaction.errors.any? %>
    <ul>
      <% @transaction.errors.full_messages.each do |msg| %>
        <li class="error"><%= msg %></li>
      <% end %>
    </ul>
  <% end %>
  <%= f.label :name %><br />
  <%= f.text_field :name %><br />
  <%= f.label :amount %><br />
  <%= f.number_field :amount %><br />
  <div class="form-group">
    <%= f.label 'Group' %>
    <select id="transaction_group_id" name="transaction[group_id]" class="custom-select" id="inputGroupSelect01">
      <option value='<%= nil%>'>None</option>
      <% Group.all.each do |group| %>
        <option value="<%= group.id %>"><%= group.name %></option>
      <% end %>
    </select>
  </div>
  <%= f.submit class: "submit text-center btn btn-primary" %>
<% end %>

app/views/transactions/edit.html.erb
<div class="form_app container">
  <h2>edit transaction</h2>
  <%= render 'form', group: @transaction %>
</div>

app/views/transactions/index.html.erb
<section class="transaction_header">
  <div class="container t-d">
    <div class="button">
      <%= link_to root_path do %>
        <i class="fa fa-bars" aria-hidden="true"></i>
      <% end %>
    </div>
    <div class="title">
      Transactions
    </div>
    <div class="search">
      <i class="fa fa-search" aria-hidden="true"></i>
    </div>
  </div>
  <h3 class ="text-center">most recent</h3>
</section>
<section class="transaction_body">
  <div class="total_amount_sec">
    <div class="amount_title">
      total amount
    </div>
    <div class="actual_total_amount">
      $ <%= @total %>
    </div>
  </div>
  <div class="container t-c">
    <% @other_transaction_sorted.each do |t| %>
      <div class="card mb-3">
        <div class="row no-gutters">
          <div class="col-md-4 grp-icn">
            <i class= "<%= t.group.icon %>" ></i>
          </div>
          <div class="col-md-8">
            <div class="card-body">
              <h5 class="card-title trns"> <%= t.name %> </h5>
              <p class="card-text style-up"> <span>$</span> <%= t.amount %></p>
              <p class="card-text"><small class="text-muted"><%= t.created_at %></small></p>
              <%= link_to "edit", edit_transaction_path(t), :class => "btn btn-primary edit_btn" %>
              <%= link_to "delete", transaction_path(t), :class => "btn btn-danger delete_grp_btn", data: {confirm: "Are you sure?"}, :method => :delete %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <br>
  <br>
  <%= link_to "Add new", new_transaction_path , :class => "btn btn-success  new_trans" %>
</section>

app/views/transactions/new.html.erb
<div class="form_app container">
  <h2>new transaction</h2>
  <%= render 'form', group: @transaction %>
</div>